export const LOAD_DEVICE_SUCCESS = 'LOAD_DEVICE_SUCCESS';

export const SENDING_MAIL = 'SENDING_MAIL';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_ERROR = 'SEND_MAIL_ERROR';
export const RESET_API_MAIL = 'RESET_API_MAIL';